/**
 * CPU-side raster buffers for frame, depth, stencil, and presentation data.
 *
 * Holds the scalar images generated by the software rasterizer and provides the
 * derived passes: inverted depth, binary stencil, and the
 * displayed framebuffer copy used by the `<img>` presenter.
 *
 * @author Ilya Tsivilskiy
 * @see FrameBuffer
 */

(function () {
  const app = window.Procerender;

  /**
   * Collection of scalar raster buffers with a fixed pixel size.
   */
  class FrameBuffer {
    /**
     * @param {number} width
     * @param {number} height
     */
    constructor(width, height) {
      this.resize(width, height);
    }

    /**
     * Resizes all raster buffers to a new resolution.
     *
     * @param {number} width
     * @param {number} height
     */
    resize(width, height) {
      this.width = width;
      this.height = height;
      this.size = width * height;
      this.frame = new Float32Array(this.size);
      this.frameResolved = new Float32Array(this.size);
      this.depth = new Float32Array(this.size);
      this.depthDisplay = new Float32Array(this.size);
      this.stencil = new Uint8Array(this.size);
    }

    /**
     * Returns the flat array index of a raster coordinate.
     *
     * @param {number} x
     * @param {number} y
     * @returns {number}
     */
    index(x, y) {
      return y * this.width + x;
    }

    /**
     * Clears the frame and depth buffers to their default background state.
     *
     * @param {number} farDepth
     */
    clear(farDepth) {
      this.frame.fill(1);
      this.frameResolved.fill(1);
      this.depth.fill(farDepth);
      this.depthDisplay.fill(0);
      this.stencil.fill(0);
    }

    /**
     * Derives the display depth map and binary stencil from the depth buffer.
     *
     * @param {number} farDepth
     */
    deriveDepthAndStencil(farDepth) {
      for (let index = 0; index < this.size; index += 1) {
        const depth = this.depth[index];
        const visible = depth < farDepth;

        // `farDepth` doubles as the clear value, so any untouched pixel still
        // equals the far plane and therefore maps to zero depth display and a
        // zero stencil bit.
        this.depthDisplay[index] = visible ? (farDepth - depth) / farDepth : 0;
        this.stencil[index] = visible ? 1 : 0;
      }
    }

    /**
     * Copies the raw frame buffer into the resolved output for presentation.
     */
    copyFrameToResolved() {
      this.frameResolved.set(this.frame);
    }
  }

  Object.assign(app, { FrameBuffer });
})();
